
#include "ape.h"
#include "../main.h"
#include "../lib/utarray.h"
#include "../lib/uthash.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

/******************************/
/*          WARNING           */
/* This file is autogenerated */
/*                            */
/******************************/

void Automato_copy(void *_dst, const void *_src) {
  Automato *dst = (Automato*)_dst, *src = (Automato*)_src;
  dst->title = src->title;
  dst->estado = src->estado;

  dst->estadosTransicoes = src->estadosTransicoes;
  dst->estadosFinais = src->estadosFinais;
}

UT_icd Automato_icd = {sizeof(Automato), NULL, Automato_copy, NULL};

APE *create_ape() {
    int push_tmp;

    /* Initialize APE */
    APE * ape = (APE*)smart_malloc(sizeof(APE));
    ape->automatos = NULL;
    utarray_new(ape->pilha, &Automato_icd);

    
    
    /* KIPPLE */
    
    Automato *KIPPLE = (Automato*)smart_malloc(sizeof(Automato));
    KIPPLE->estadosTransicoes = NULL;
    KIPPLE->title = "KIPPLE";
    KIPPLE->estado = 0;
    utarray_new(KIPPLE->estadosFinais, &ut_int_icd);


    
    push_tmp = 1; utarray_push_back(KIPPLE->estadosFinais, &push_tmp);


    
    Estado *KIPPLE0 = (Estado*)smart_malloc(sizeof(Estado));
    KIPPLE0->transicoes = NULL;
    KIPPLE0->chamadas = NULL;
    KIPPLE0->estado = 0;
    HASH_ADD_INT(KIPPLE->estadosTransicoes, estado, KIPPLE0);

    
    
    TransicaoChamada *KIPPLE0_C1 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    KIPPLE0_C1->token = "STACK_IDENTIFIER";
    KIPPLE0_C1->submaquina = "CODE";
    KIPPLE0_C1->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, KIPPLE0->chamadas, KIPPLE0_C1->token, strlen(KIPPLE0_C1->token), KIPPLE0_C1);

    TransicaoChamada *KIPPLE0_C2 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    KIPPLE0_C2->token = "(";
    KIPPLE0_C2->submaquina = "CODE";
    KIPPLE0_C2->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, KIPPLE0->chamadas, KIPPLE0_C2->token, strlen(KIPPLE0_C2->token), KIPPLE0_C2);

    TransicaoChamada *KIPPLE0_C3 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    KIPPLE0_C3->token = "NUMBER";
    KIPPLE0_C3->submaquina = "CODE";
    KIPPLE0_C3->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, KIPPLE0->chamadas, KIPPLE0_C3->token, strlen(KIPPLE0_C3->token), KIPPLE0_C3);


    Estado *KIPPLE1 = (Estado*)smart_malloc(sizeof(Estado));
    KIPPLE1->transicoes = NULL;
    KIPPLE1->chamadas = NULL;
    KIPPLE1->estado = 1;
    HASH_ADD_INT(KIPPLE->estadosTransicoes, estado, KIPPLE1);

    
    
    TransicaoChamada *KIPPLE1_C1 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    KIPPLE1_C1->token = "STACK_IDENTIFIER";
    KIPPLE1_C1->submaquina = "CODE";
    KIPPLE1_C1->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, KIPPLE1->chamadas, KIPPLE1_C1->token, strlen(KIPPLE1_C1->token), KIPPLE1_C1);

    TransicaoChamada *KIPPLE1_C2 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    KIPPLE1_C2->token = "(";
    KIPPLE1_C2->submaquina = "CODE";
    KIPPLE1_C2->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, KIPPLE1->chamadas, KIPPLE1_C2->token, strlen(KIPPLE1_C2->token), KIPPLE1_C2);

    TransicaoChamada *KIPPLE1_C3 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    KIPPLE1_C3->token = "NUMBER";
    KIPPLE1_C3->submaquina = "CODE";
    KIPPLE1_C3->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, KIPPLE1->chamadas, KIPPLE1_C3->token, strlen(KIPPLE1_C3->token), KIPPLE1_C3);



    HASH_ADD_KEYPTR(hh, ape->automatos, KIPPLE->title, strlen(KIPPLE->title), KIPPLE);


    ape->automatoAtual = KIPPLE;


    
    /* CODE */
    
    Automato *CODE = (Automato*)smart_malloc(sizeof(Automato));
    CODE->estadosTransicoes = NULL;
    CODE->title = "CODE";
    CODE->estado = 0;
    utarray_new(CODE->estadosFinais, &ut_int_icd);


    
    push_tmp = 1; utarray_push_back(CODE->estadosFinais, &push_tmp);


    
    Estado *CODE0 = (Estado*)smart_malloc(sizeof(Estado));
    CODE0->transicoes = NULL;
    CODE0->chamadas = NULL;
    CODE0->estado = 0;
    HASH_ADD_INT(CODE->estadosTransicoes, estado, CODE0);

    
    
    TransicaoChamada *CODE0_C1 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    CODE0_C1->token = "STACK_IDENTIFIER";
    CODE0_C1->submaquina = "EXPRESSION";
    CODE0_C1->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, CODE0->chamadas, CODE0_C1->token, strlen(CODE0_C1->token), CODE0_C1);

    TransicaoChamada *CODE0_C2 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    CODE0_C2->token = "(";
    CODE0_C2->submaquina = "LOOP";
    CODE0_C2->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, CODE0->chamadas, CODE0_C2->token, strlen(CODE0_C2->token), CODE0_C2);

    TransicaoChamada *CODE0_C3 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    CODE0_C3->token = "NUMBER";
    CODE0_C3->submaquina = "EXPRESSION";
    CODE0_C3->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, CODE0->chamadas, CODE0_C3->token, strlen(CODE0_C3->token), CODE0_C3);



    HASH_ADD_KEYPTR(hh, ape->automatos, CODE->title, strlen(CODE->title), CODE);

    /* PUSH_L */
    
    Automato *PUSH_L = (Automato*)smart_malloc(sizeof(Automato));
    PUSH_L->estadosTransicoes = NULL;
    PUSH_L->title = "PUSH_L";
    PUSH_L->estado = 0;
    utarray_new(PUSH_L->estadosFinais, &ut_int_icd);


    
    push_tmp = 2; utarray_push_back(PUSH_L->estadosFinais, &push_tmp);

    push_tmp = 3; utarray_push_back(PUSH_L->estadosFinais, &push_tmp);

    push_tmp = 4; utarray_push_back(PUSH_L->estadosFinais, &push_tmp);


    
    Estado *PUSH_L0 = (Estado*)smart_malloc(sizeof(Estado));
    PUSH_L0->transicoes = NULL;
    PUSH_L0->chamadas = NULL;
    PUSH_L0->estado = 0;
    HASH_ADD_INT(PUSH_L->estadosTransicoes, estado, PUSH_L0);

    
    Transicao *PUSH_L0_T1 = (Transicao*)smart_malloc(sizeof(Transicao));
    PUSH_L0_T1->token = "<";
    PUSH_L0_T1->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, PUSH_L0->transicoes, PUSH_L0_T1->token, strlen(PUSH_L0_T1->token), PUSH_L0_T1);

    

    Estado *PUSH_L1 = (Estado*)smart_malloc(sizeof(Estado));
    PUSH_L1->transicoes = NULL;
    PUSH_L1->chamadas = NULL;
    PUSH_L1->estado = 1;
    HASH_ADD_INT(PUSH_L->estadosTransicoes, estado, PUSH_L1);

    
    
    TransicaoChamada *PUSH_L1_C1 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    PUSH_L1_C1->token = "STACK_IDENTIFIER";
    PUSH_L1_C1->submaquina = "STACK_IDENTIFIER";
    PUSH_L1_C1->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, PUSH_L1->chamadas, PUSH_L1_C1->token, strlen(PUSH_L1_C1->token), PUSH_L1_C1);

    TransicaoChamada *PUSH_L1_C2 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    PUSH_L1_C2->token = "NUMBER";
    PUSH_L1_C2->submaquina = "NUMBER";
    PUSH_L1_C2->estadoResultado = 2;
    HASH_ADD_KEYPTR(hh, PUSH_L1->chamadas, PUSH_L1_C2->token, strlen(PUSH_L1_C2->token), PUSH_L1_C2);


    Estado *PUSH_L2 = (Estado*)smart_malloc(sizeof(Estado));
    PUSH_L2->transicoes = NULL;
    PUSH_L2->chamadas = NULL;
    PUSH_L2->estado = 2;
    HASH_ADD_INT(PUSH_L->estadosTransicoes, estado, PUSH_L2);

    
    
    TransicaoChamada *PUSH_L2_C1 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    PUSH_L2_C1->token = ">";
    PUSH_L2_C1->submaquina = "PUSH_R";
    PUSH_L2_C1->estadoResultado = 4;
    HASH_ADD_KEYPTR(hh, PUSH_L2->chamadas, PUSH_L2_C1->token, strlen(PUSH_L2_C1->token), PUSH_L2_C1);


    Estado *PUSH_L3 = (Estado*)smart_malloc(sizeof(Estado));
    PUSH_L3->transicoes = NULL;
    PUSH_L3->chamadas = NULL;
    PUSH_L3->estado = 3;
    HASH_ADD_INT(PUSH_L->estadosTransicoes, estado, PUSH_L3);

    
    
    TransicaoChamada *PUSH_L3_C1 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    PUSH_L3_C1->token = "?";
    PUSH_L3_C1->submaquina = "CLEAR";
    PUSH_L3_C1->estadoResultado = 4;
    HASH_ADD_KEYPTR(hh, PUSH_L3->chamadas, PUSH_L3_C1->token, strlen(PUSH_L3_C1->token), PUSH_L3_C1);

    TransicaoChamada *PUSH_L3_C2 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    PUSH_L3_C2->token = "+";
    PUSH_L3_C2->submaquina = "ADD_SUB";
    PUSH_L3_C2->estadoResultado = 4;
    HASH_ADD_KEYPTR(hh, PUSH_L3->chamadas, PUSH_L3_C2->token, strlen(PUSH_L3_C2->token), PUSH_L3_C2);

    TransicaoChamada *PUSH_L3_C3 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    PUSH_L3_C3->token = ">";
    PUSH_L3_C3->submaquina = "PUSH_R";
    PUSH_L3_C3->estadoResultado = 4;
    HASH_ADD_KEYPTR(hh, PUSH_L3->chamadas, PUSH_L3_C3->token, strlen(PUSH_L3_C3->token), PUSH_L3_C3);

    TransicaoChamada *PUSH_L3_C4 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    PUSH_L3_C4->token = "-";
    PUSH_L3_C4->submaquina = "ADD_SUB";
    PUSH_L3_C4->estadoResultado = 4;
    HASH_ADD_KEYPTR(hh, PUSH_L3->chamadas, PUSH_L3_C4->token, strlen(PUSH_L3_C4->token), PUSH_L3_C4);

    TransicaoChamada *PUSH_L3_C5 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    PUSH_L3_C5->token = "<";
    PUSH_L3_C5->submaquina = "PUSH_L";
    PUSH_L3_C5->estadoResultado = 4;
    HASH_ADD_KEYPTR(hh, PUSH_L3->chamadas, PUSH_L3_C5->token, strlen(PUSH_L3_C5->token), PUSH_L3_C5);



    HASH_ADD_KEYPTR(hh, ape->automatos, PUSH_L->title, strlen(PUSH_L->title), PUSH_L);

    /* EXPRESSION */
    
    Automato *EXPRESSION = (Automato*)smart_malloc(sizeof(Automato));
    EXPRESSION->estadosTransicoes = NULL;
    EXPRESSION->title = "EXPRESSION";
    EXPRESSION->estado = 0;
    utarray_new(EXPRESSION->estadosFinais, &ut_int_icd);


    
    push_tmp = 3; utarray_push_back(EXPRESSION->estadosFinais, &push_tmp);

    push_tmp = 5; utarray_push_back(EXPRESSION->estadosFinais, &push_tmp);


    
    Estado *EXPRESSION5 = (Estado*)smart_malloc(sizeof(Estado));
    EXPRESSION5->transicoes = NULL;
    EXPRESSION5->chamadas = NULL;
    EXPRESSION5->estado = 5;
    HASH_ADD_INT(EXPRESSION->estadosTransicoes, estado, EXPRESSION5);

    
    
    TransicaoChamada *EXPRESSION5_C1 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    EXPRESSION5_C1->token = "+";
    EXPRESSION5_C1->submaquina = "OPERATIONS";
    EXPRESSION5_C1->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, EXPRESSION5->chamadas, EXPRESSION5_C1->token, strlen(EXPRESSION5_C1->token), EXPRESSION5_C1);

    TransicaoChamada *EXPRESSION5_C2 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    EXPRESSION5_C2->token = "?";
    EXPRESSION5_C2->submaquina = "OPERATIONS";
    EXPRESSION5_C2->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, EXPRESSION5->chamadas, EXPRESSION5_C2->token, strlen(EXPRESSION5_C2->token), EXPRESSION5_C2);

    TransicaoChamada *EXPRESSION5_C3 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    EXPRESSION5_C3->token = ">";
    EXPRESSION5_C3->submaquina = "OPERATIONS";
    EXPRESSION5_C3->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, EXPRESSION5->chamadas, EXPRESSION5_C3->token, strlen(EXPRESSION5_C3->token), EXPRESSION5_C3);

    TransicaoChamada *EXPRESSION5_C4 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    EXPRESSION5_C4->token = "-";
    EXPRESSION5_C4->submaquina = "OPERATIONS";
    EXPRESSION5_C4->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, EXPRESSION5->chamadas, EXPRESSION5_C4->token, strlen(EXPRESSION5_C4->token), EXPRESSION5_C4);

    TransicaoChamada *EXPRESSION5_C5 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    EXPRESSION5_C5->token = "<";
    EXPRESSION5_C5->submaquina = "OPERATIONS";
    EXPRESSION5_C5->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, EXPRESSION5->chamadas, EXPRESSION5_C5->token, strlen(EXPRESSION5_C5->token), EXPRESSION5_C5);


    Estado *EXPRESSION0 = (Estado*)smart_malloc(sizeof(Estado));
    EXPRESSION0->transicoes = NULL;
    EXPRESSION0->chamadas = NULL;
    EXPRESSION0->estado = 0;
    HASH_ADD_INT(EXPRESSION->estadosTransicoes, estado, EXPRESSION0);

    
    
    TransicaoChamada *EXPRESSION0_C1 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    EXPRESSION0_C1->token = "STACK_IDENTIFIER";
    EXPRESSION0_C1->submaquina = "STACK_IDENTIFIER";
    EXPRESSION0_C1->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, EXPRESSION0->chamadas, EXPRESSION0_C1->token, strlen(EXPRESSION0_C1->token), EXPRESSION0_C1);

    TransicaoChamada *EXPRESSION0_C2 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    EXPRESSION0_C2->token = "NUMBER";
    EXPRESSION0_C2->submaquina = "NUMBER";
    EXPRESSION0_C2->estadoResultado = 2;
    HASH_ADD_KEYPTR(hh, EXPRESSION0->chamadas, EXPRESSION0_C2->token, strlen(EXPRESSION0_C2->token), EXPRESSION0_C2);


    Estado *EXPRESSION1 = (Estado*)smart_malloc(sizeof(Estado));
    EXPRESSION1->transicoes = NULL;
    EXPRESSION1->chamadas = NULL;
    EXPRESSION1->estado = 1;
    HASH_ADD_INT(EXPRESSION->estadosTransicoes, estado, EXPRESSION1);

    
    
    TransicaoChamada *EXPRESSION1_C1 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    EXPRESSION1_C1->token = "+";
    EXPRESSION1_C1->submaquina = "OPERATIONS";
    EXPRESSION1_C1->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, EXPRESSION1->chamadas, EXPRESSION1_C1->token, strlen(EXPRESSION1_C1->token), EXPRESSION1_C1);

    TransicaoChamada *EXPRESSION1_C2 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    EXPRESSION1_C2->token = "?";
    EXPRESSION1_C2->submaquina = "OPERATIONS";
    EXPRESSION1_C2->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, EXPRESSION1->chamadas, EXPRESSION1_C2->token, strlen(EXPRESSION1_C2->token), EXPRESSION1_C2);

    TransicaoChamada *EXPRESSION1_C3 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    EXPRESSION1_C3->token = ">";
    EXPRESSION1_C3->submaquina = "OPERATIONS";
    EXPRESSION1_C3->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, EXPRESSION1->chamadas, EXPRESSION1_C3->token, strlen(EXPRESSION1_C3->token), EXPRESSION1_C3);

    TransicaoChamada *EXPRESSION1_C4 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    EXPRESSION1_C4->token = "-";
    EXPRESSION1_C4->submaquina = "OPERATIONS";
    EXPRESSION1_C4->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, EXPRESSION1->chamadas, EXPRESSION1_C4->token, strlen(EXPRESSION1_C4->token), EXPRESSION1_C4);

    TransicaoChamada *EXPRESSION1_C5 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    EXPRESSION1_C5->token = "<";
    EXPRESSION1_C5->submaquina = "OPERATIONS";
    EXPRESSION1_C5->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, EXPRESSION1->chamadas, EXPRESSION1_C5->token, strlen(EXPRESSION1_C5->token), EXPRESSION1_C5);


    Estado *EXPRESSION2 = (Estado*)smart_malloc(sizeof(Estado));
    EXPRESSION2->transicoes = NULL;
    EXPRESSION2->chamadas = NULL;
    EXPRESSION2->estado = 2;
    HASH_ADD_INT(EXPRESSION->estadosTransicoes, estado, EXPRESSION2);

    
    Transicao *EXPRESSION2_T1 = (Transicao*)smart_malloc(sizeof(Transicao));
    EXPRESSION2_T1->token = ">";
    EXPRESSION2_T1->estadoResultado = 4;
    HASH_ADD_KEYPTR(hh, EXPRESSION2->transicoes, EXPRESSION2_T1->token, strlen(EXPRESSION2_T1->token), EXPRESSION2_T1);

    

    Estado *EXPRESSION4 = (Estado*)smart_malloc(sizeof(Estado));
    EXPRESSION4->transicoes = NULL;
    EXPRESSION4->chamadas = NULL;
    EXPRESSION4->estado = 4;
    HASH_ADD_INT(EXPRESSION->estadosTransicoes, estado, EXPRESSION4);

    
    
    TransicaoChamada *EXPRESSION4_C1 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    EXPRESSION4_C1->token = "STACK_IDENTIFIER";
    EXPRESSION4_C1->submaquina = "STACK_IDENTIFIER";
    EXPRESSION4_C1->estadoResultado = 5;
    HASH_ADD_KEYPTR(hh, EXPRESSION4->chamadas, EXPRESSION4_C1->token, strlen(EXPRESSION4_C1->token), EXPRESSION4_C1);



    HASH_ADD_KEYPTR(hh, ape->automatos, EXPRESSION->title, strlen(EXPRESSION->title), EXPRESSION);

    /* OPERATIONS */
    
    Automato *OPERATIONS = (Automato*)smart_malloc(sizeof(Automato));
    OPERATIONS->estadosTransicoes = NULL;
    OPERATIONS->title = "OPERATIONS";
    OPERATIONS->estado = 0;
    utarray_new(OPERATIONS->estadosFinais, &ut_int_icd);


    
    push_tmp = 1; utarray_push_back(OPERATIONS->estadosFinais, &push_tmp);


    
    Estado *OPERATIONS0 = (Estado*)smart_malloc(sizeof(Estado));
    OPERATIONS0->transicoes = NULL;
    OPERATIONS0->chamadas = NULL;
    OPERATIONS0->estado = 0;
    HASH_ADD_INT(OPERATIONS->estadosTransicoes, estado, OPERATIONS0);

    
    
    TransicaoChamada *OPERATIONS0_C1 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    OPERATIONS0_C1->token = "?";
    OPERATIONS0_C1->submaquina = "CLEAR";
    OPERATIONS0_C1->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, OPERATIONS0->chamadas, OPERATIONS0_C1->token, strlen(OPERATIONS0_C1->token), OPERATIONS0_C1);

    TransicaoChamada *OPERATIONS0_C2 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    OPERATIONS0_C2->token = "+";
    OPERATIONS0_C2->submaquina = "ADD_SUB";
    OPERATIONS0_C2->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, OPERATIONS0->chamadas, OPERATIONS0_C2->token, strlen(OPERATIONS0_C2->token), OPERATIONS0_C2);

    TransicaoChamada *OPERATIONS0_C3 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    OPERATIONS0_C3->token = ">";
    OPERATIONS0_C3->submaquina = "PUSH_R";
    OPERATIONS0_C3->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, OPERATIONS0->chamadas, OPERATIONS0_C3->token, strlen(OPERATIONS0_C3->token), OPERATIONS0_C3);

    TransicaoChamada *OPERATIONS0_C4 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    OPERATIONS0_C4->token = "-";
    OPERATIONS0_C4->submaquina = "ADD_SUB";
    OPERATIONS0_C4->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, OPERATIONS0->chamadas, OPERATIONS0_C4->token, strlen(OPERATIONS0_C4->token), OPERATIONS0_C4);

    TransicaoChamada *OPERATIONS0_C5 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    OPERATIONS0_C5->token = "<";
    OPERATIONS0_C5->submaquina = "PUSH_L";
    OPERATIONS0_C5->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, OPERATIONS0->chamadas, OPERATIONS0_C5->token, strlen(OPERATIONS0_C5->token), OPERATIONS0_C5);



    HASH_ADD_KEYPTR(hh, ape->automatos, OPERATIONS->title, strlen(OPERATIONS->title), OPERATIONS);

    /* LOOP */
    
    Automato *LOOP = (Automato*)smart_malloc(sizeof(Automato));
    LOOP->estadosTransicoes = NULL;
    LOOP->title = "LOOP";
    LOOP->estado = 0;
    utarray_new(LOOP->estadosFinais, &ut_int_icd);


    
    push_tmp = 4; utarray_push_back(LOOP->estadosFinais, &push_tmp);


    
    Estado *LOOP0 = (Estado*)smart_malloc(sizeof(Estado));
    LOOP0->transicoes = NULL;
    LOOP0->chamadas = NULL;
    LOOP0->estado = 0;
    HASH_ADD_INT(LOOP->estadosTransicoes, estado, LOOP0);

    
    Transicao *LOOP0_T1 = (Transicao*)smart_malloc(sizeof(Transicao));
    LOOP0_T1->token = "(";
    LOOP0_T1->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, LOOP0->transicoes, LOOP0_T1->token, strlen(LOOP0_T1->token), LOOP0_T1);

    

    Estado *LOOP1 = (Estado*)smart_malloc(sizeof(Estado));
    LOOP1->transicoes = NULL;
    LOOP1->chamadas = NULL;
    LOOP1->estado = 1;
    HASH_ADD_INT(LOOP->estadosTransicoes, estado, LOOP1);

    
    
    TransicaoChamada *LOOP1_C1 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    LOOP1_C1->token = "STACK_IDENTIFIER";
    LOOP1_C1->submaquina = "STACK_IDENTIFIER";
    LOOP1_C1->estadoResultado = 2;
    HASH_ADD_KEYPTR(hh, LOOP1->chamadas, LOOP1_C1->token, strlen(LOOP1_C1->token), LOOP1_C1);


    Estado *LOOP2 = (Estado*)smart_malloc(sizeof(Estado));
    LOOP2->transicoes = NULL;
    LOOP2->chamadas = NULL;
    LOOP2->estado = 2;
    HASH_ADD_INT(LOOP->estadosTransicoes, estado, LOOP2);

    
    Transicao *LOOP2_T1 = (Transicao*)smart_malloc(sizeof(Transicao));
    LOOP2_T1->token = ")";
    LOOP2_T1->estadoResultado = 4;
    HASH_ADD_KEYPTR(hh, LOOP2->transicoes, LOOP2_T1->token, strlen(LOOP2_T1->token), LOOP2_T1);

    
    TransicaoChamada *LOOP2_C1 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    LOOP2_C1->token = "?";
    LOOP2_C1->submaquina = "OPERATIONS";
    LOOP2_C1->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, LOOP2->chamadas, LOOP2_C1->token, strlen(LOOP2_C1->token), LOOP2_C1);

    TransicaoChamada *LOOP2_C2 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    LOOP2_C2->token = "NUMBER";
    LOOP2_C2->submaquina = "CODE";
    LOOP2_C2->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, LOOP2->chamadas, LOOP2_C2->token, strlen(LOOP2_C2->token), LOOP2_C2);

    TransicaoChamada *LOOP2_C3 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    LOOP2_C3->token = ">";
    LOOP2_C3->submaquina = "OPERATIONS";
    LOOP2_C3->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, LOOP2->chamadas, LOOP2_C3->token, strlen(LOOP2_C3->token), LOOP2_C3);

    TransicaoChamada *LOOP2_C4 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    LOOP2_C4->token = "<";
    LOOP2_C4->submaquina = "OPERATIONS";
    LOOP2_C4->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, LOOP2->chamadas, LOOP2_C4->token, strlen(LOOP2_C4->token), LOOP2_C4);

    TransicaoChamada *LOOP2_C5 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    LOOP2_C5->token = "STACK_IDENTIFIER";
    LOOP2_C5->submaquina = "CODE";
    LOOP2_C5->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, LOOP2->chamadas, LOOP2_C5->token, strlen(LOOP2_C5->token), LOOP2_C5);

    TransicaoChamada *LOOP2_C6 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    LOOP2_C6->token = "+";
    LOOP2_C6->submaquina = "OPERATIONS";
    LOOP2_C6->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, LOOP2->chamadas, LOOP2_C6->token, strlen(LOOP2_C6->token), LOOP2_C6);

    TransicaoChamada *LOOP2_C7 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    LOOP2_C7->token = "(";
    LOOP2_C7->submaquina = "CODE";
    LOOP2_C7->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, LOOP2->chamadas, LOOP2_C7->token, strlen(LOOP2_C7->token), LOOP2_C7);

    TransicaoChamada *LOOP2_C8 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    LOOP2_C8->token = "-";
    LOOP2_C8->submaquina = "OPERATIONS";
    LOOP2_C8->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, LOOP2->chamadas, LOOP2_C8->token, strlen(LOOP2_C8->token), LOOP2_C8);


    Estado *LOOP3 = (Estado*)smart_malloc(sizeof(Estado));
    LOOP3->transicoes = NULL;
    LOOP3->chamadas = NULL;
    LOOP3->estado = 3;
    HASH_ADD_INT(LOOP->estadosTransicoes, estado, LOOP3);

    
    Transicao *LOOP3_T1 = (Transicao*)smart_malloc(sizeof(Transicao));
    LOOP3_T1->token = ")";
    LOOP3_T1->estadoResultado = 4;
    HASH_ADD_KEYPTR(hh, LOOP3->transicoes, LOOP3_T1->token, strlen(LOOP3_T1->token), LOOP3_T1);

    
    TransicaoChamada *LOOP3_C1 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    LOOP3_C1->token = "STACK_IDENTIFIER";
    LOOP3_C1->submaquina = "CODE";
    LOOP3_C1->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, LOOP3->chamadas, LOOP3_C1->token, strlen(LOOP3_C1->token), LOOP3_C1);

    TransicaoChamada *LOOP3_C2 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    LOOP3_C2->token = "(";
    LOOP3_C2->submaquina = "CODE";
    LOOP3_C2->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, LOOP3->chamadas, LOOP3_C2->token, strlen(LOOP3_C2->token), LOOP3_C2);

    TransicaoChamada *LOOP3_C3 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    LOOP3_C3->token = "NUMBER";
    LOOP3_C3->submaquina = "CODE";
    LOOP3_C3->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, LOOP3->chamadas, LOOP3_C3->token, strlen(LOOP3_C3->token), LOOP3_C3);



    HASH_ADD_KEYPTR(hh, ape->automatos, LOOP->title, strlen(LOOP->title), LOOP);

    /* DIGIT */
    
    Automato *DIGIT = (Automato*)smart_malloc(sizeof(Automato));
    DIGIT->estadosTransicoes = NULL;
    DIGIT->title = "DIGIT";
    DIGIT->estado = 0;
    utarray_new(DIGIT->estadosFinais, &ut_int_icd);


    
    push_tmp = 1; utarray_push_back(DIGIT->estadosFinais, &push_tmp);


    
    Estado *DIGIT0 = (Estado*)smart_malloc(sizeof(Estado));
    DIGIT0->transicoes = NULL;
    DIGIT0->chamadas = NULL;
    DIGIT0->estado = 0;
    HASH_ADD_INT(DIGIT->estadosTransicoes, estado, DIGIT0);

    
    Transicao *DIGIT0_T1 = (Transicao*)smart_malloc(sizeof(Transicao));
    DIGIT0_T1->token = "9";
    DIGIT0_T1->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, DIGIT0->transicoes, DIGIT0_T1->token, strlen(DIGIT0_T1->token), DIGIT0_T1);

    Transicao *DIGIT0_T2 = (Transicao*)smart_malloc(sizeof(Transicao));
    DIGIT0_T2->token = "0";
    DIGIT0_T2->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, DIGIT0->transicoes, DIGIT0_T2->token, strlen(DIGIT0_T2->token), DIGIT0_T2);

    Transicao *DIGIT0_T3 = (Transicao*)smart_malloc(sizeof(Transicao));
    DIGIT0_T3->token = "2";
    DIGIT0_T3->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, DIGIT0->transicoes, DIGIT0_T3->token, strlen(DIGIT0_T3->token), DIGIT0_T3);

    Transicao *DIGIT0_T4 = (Transicao*)smart_malloc(sizeof(Transicao));
    DIGIT0_T4->token = "3";
    DIGIT0_T4->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, DIGIT0->transicoes, DIGIT0_T4->token, strlen(DIGIT0_T4->token), DIGIT0_T4);

    Transicao *DIGIT0_T5 = (Transicao*)smart_malloc(sizeof(Transicao));
    DIGIT0_T5->token = "7";
    DIGIT0_T5->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, DIGIT0->transicoes, DIGIT0_T5->token, strlen(DIGIT0_T5->token), DIGIT0_T5);

    Transicao *DIGIT0_T6 = (Transicao*)smart_malloc(sizeof(Transicao));
    DIGIT0_T6->token = "6";
    DIGIT0_T6->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, DIGIT0->transicoes, DIGIT0_T6->token, strlen(DIGIT0_T6->token), DIGIT0_T6);

    Transicao *DIGIT0_T7 = (Transicao*)smart_malloc(sizeof(Transicao));
    DIGIT0_T7->token = "5";
    DIGIT0_T7->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, DIGIT0->transicoes, DIGIT0_T7->token, strlen(DIGIT0_T7->token), DIGIT0_T7);

    Transicao *DIGIT0_T8 = (Transicao*)smart_malloc(sizeof(Transicao));
    DIGIT0_T8->token = "1";
    DIGIT0_T8->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, DIGIT0->transicoes, DIGIT0_T8->token, strlen(DIGIT0_T8->token), DIGIT0_T8);

    Transicao *DIGIT0_T9 = (Transicao*)smart_malloc(sizeof(Transicao));
    DIGIT0_T9->token = "8";
    DIGIT0_T9->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, DIGIT0->transicoes, DIGIT0_T9->token, strlen(DIGIT0_T9->token), DIGIT0_T9);

    Transicao *DIGIT0_T10 = (Transicao*)smart_malloc(sizeof(Transicao));
    DIGIT0_T10->token = "4";
    DIGIT0_T10->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, DIGIT0->transicoes, DIGIT0_T10->token, strlen(DIGIT0_T10->token), DIGIT0_T10);

    


    HASH_ADD_KEYPTR(hh, ape->automatos, DIGIT->title, strlen(DIGIT->title), DIGIT);

    /* CLEAR */
    
    Automato *CLEAR = (Automato*)smart_malloc(sizeof(Automato));
    CLEAR->estadosTransicoes = NULL;
    CLEAR->title = "CLEAR";
    CLEAR->estado = 0;
    utarray_new(CLEAR->estadosFinais, &ut_int_icd);


    
    push_tmp = 1; utarray_push_back(CLEAR->estadosFinais, &push_tmp);


    
    Estado *CLEAR0 = (Estado*)smart_malloc(sizeof(Estado));
    CLEAR0->transicoes = NULL;
    CLEAR0->chamadas = NULL;
    CLEAR0->estado = 0;
    HASH_ADD_INT(CLEAR->estadosTransicoes, estado, CLEAR0);

    
    Transicao *CLEAR0_T1 = (Transicao*)smart_malloc(sizeof(Transicao));
    CLEAR0_T1->token = "?";
    CLEAR0_T1->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, CLEAR0->transicoes, CLEAR0_T1->token, strlen(CLEAR0_T1->token), CLEAR0_T1);

    


    HASH_ADD_KEYPTR(hh, ape->automatos, CLEAR->title, strlen(CLEAR->title), CLEAR);

    /* ADD_SUB */
    
    Automato *ADD_SUB = (Automato*)smart_malloc(sizeof(Automato));
    ADD_SUB->estadosTransicoes = NULL;
    ADD_SUB->title = "ADD_SUB";
    ADD_SUB->estado = 0;
    utarray_new(ADD_SUB->estadosFinais, &ut_int_icd);


    
    push_tmp = 2; utarray_push_back(ADD_SUB->estadosFinais, &push_tmp);

    push_tmp = 3; utarray_push_back(ADD_SUB->estadosFinais, &push_tmp);

    push_tmp = 4; utarray_push_back(ADD_SUB->estadosFinais, &push_tmp);


    
    Estado *ADD_SUB0 = (Estado*)smart_malloc(sizeof(Estado));
    ADD_SUB0->transicoes = NULL;
    ADD_SUB0->chamadas = NULL;
    ADD_SUB0->estado = 0;
    HASH_ADD_INT(ADD_SUB->estadosTransicoes, estado, ADD_SUB0);

    
    Transicao *ADD_SUB0_T1 = (Transicao*)smart_malloc(sizeof(Transicao));
    ADD_SUB0_T1->token = "+";
    ADD_SUB0_T1->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, ADD_SUB0->transicoes, ADD_SUB0_T1->token, strlen(ADD_SUB0_T1->token), ADD_SUB0_T1);

    Transicao *ADD_SUB0_T2 = (Transicao*)smart_malloc(sizeof(Transicao));
    ADD_SUB0_T2->token = "-";
    ADD_SUB0_T2->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, ADD_SUB0->transicoes, ADD_SUB0_T2->token, strlen(ADD_SUB0_T2->token), ADD_SUB0_T2);

    

    Estado *ADD_SUB1 = (Estado*)smart_malloc(sizeof(Estado));
    ADD_SUB1->transicoes = NULL;
    ADD_SUB1->chamadas = NULL;
    ADD_SUB1->estado = 1;
    HASH_ADD_INT(ADD_SUB->estadosTransicoes, estado, ADD_SUB1);

    
    
    TransicaoChamada *ADD_SUB1_C1 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    ADD_SUB1_C1->token = "STACK_IDENTIFIER";
    ADD_SUB1_C1->submaquina = "STACK_IDENTIFIER";
    ADD_SUB1_C1->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, ADD_SUB1->chamadas, ADD_SUB1_C1->token, strlen(ADD_SUB1_C1->token), ADD_SUB1_C1);

    TransicaoChamada *ADD_SUB1_C2 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    ADD_SUB1_C2->token = "NUMBER";
    ADD_SUB1_C2->submaquina = "NUMBER";
    ADD_SUB1_C2->estadoResultado = 2;
    HASH_ADD_KEYPTR(hh, ADD_SUB1->chamadas, ADD_SUB1_C2->token, strlen(ADD_SUB1_C2->token), ADD_SUB1_C2);


    Estado *ADD_SUB2 = (Estado*)smart_malloc(sizeof(Estado));
    ADD_SUB2->transicoes = NULL;
    ADD_SUB2->chamadas = NULL;
    ADD_SUB2->estado = 2;
    HASH_ADD_INT(ADD_SUB->estadosTransicoes, estado, ADD_SUB2);

    
    
    TransicaoChamada *ADD_SUB2_C1 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    ADD_SUB2_C1->token = ">";
    ADD_SUB2_C1->submaquina = "PUSH_R";
    ADD_SUB2_C1->estadoResultado = 4;
    HASH_ADD_KEYPTR(hh, ADD_SUB2->chamadas, ADD_SUB2_C1->token, strlen(ADD_SUB2_C1->token), ADD_SUB2_C1);


    Estado *ADD_SUB3 = (Estado*)smart_malloc(sizeof(Estado));
    ADD_SUB3->transicoes = NULL;
    ADD_SUB3->chamadas = NULL;
    ADD_SUB3->estado = 3;
    HASH_ADD_INT(ADD_SUB->estadosTransicoes, estado, ADD_SUB3);

    
    
    TransicaoChamada *ADD_SUB3_C1 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    ADD_SUB3_C1->token = "?";
    ADD_SUB3_C1->submaquina = "CLEAR";
    ADD_SUB3_C1->estadoResultado = 4;
    HASH_ADD_KEYPTR(hh, ADD_SUB3->chamadas, ADD_SUB3_C1->token, strlen(ADD_SUB3_C1->token), ADD_SUB3_C1);

    TransicaoChamada *ADD_SUB3_C2 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    ADD_SUB3_C2->token = "+";
    ADD_SUB3_C2->submaquina = "ADD_SUB";
    ADD_SUB3_C2->estadoResultado = 4;
    HASH_ADD_KEYPTR(hh, ADD_SUB3->chamadas, ADD_SUB3_C2->token, strlen(ADD_SUB3_C2->token), ADD_SUB3_C2);

    TransicaoChamada *ADD_SUB3_C3 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    ADD_SUB3_C3->token = ">";
    ADD_SUB3_C3->submaquina = "PUSH_R";
    ADD_SUB3_C3->estadoResultado = 4;
    HASH_ADD_KEYPTR(hh, ADD_SUB3->chamadas, ADD_SUB3_C3->token, strlen(ADD_SUB3_C3->token), ADD_SUB3_C3);

    TransicaoChamada *ADD_SUB3_C4 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    ADD_SUB3_C4->token = "-";
    ADD_SUB3_C4->submaquina = "ADD_SUB";
    ADD_SUB3_C4->estadoResultado = 4;
    HASH_ADD_KEYPTR(hh, ADD_SUB3->chamadas, ADD_SUB3_C4->token, strlen(ADD_SUB3_C4->token), ADD_SUB3_C4);

    TransicaoChamada *ADD_SUB3_C5 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    ADD_SUB3_C5->token = "<";
    ADD_SUB3_C5->submaquina = "PUSH_L";
    ADD_SUB3_C5->estadoResultado = 4;
    HASH_ADD_KEYPTR(hh, ADD_SUB3->chamadas, ADD_SUB3_C5->token, strlen(ADD_SUB3_C5->token), ADD_SUB3_C5);



    HASH_ADD_KEYPTR(hh, ape->automatos, ADD_SUB->title, strlen(ADD_SUB->title), ADD_SUB);

    /* PUSH_R */
    
    Automato *PUSH_R = (Automato*)smart_malloc(sizeof(Automato));
    PUSH_R->estadosTransicoes = NULL;
    PUSH_R->title = "PUSH_R";
    PUSH_R->estado = 0;
    utarray_new(PUSH_R->estadosFinais, &ut_int_icd);


    
    push_tmp = 2; utarray_push_back(PUSH_R->estadosFinais, &push_tmp);

    push_tmp = 3; utarray_push_back(PUSH_R->estadosFinais, &push_tmp);


    
    Estado *PUSH_R0 = (Estado*)smart_malloc(sizeof(Estado));
    PUSH_R0->transicoes = NULL;
    PUSH_R0->chamadas = NULL;
    PUSH_R0->estado = 0;
    HASH_ADD_INT(PUSH_R->estadosTransicoes, estado, PUSH_R0);

    
    Transicao *PUSH_R0_T1 = (Transicao*)smart_malloc(sizeof(Transicao));
    PUSH_R0_T1->token = ">";
    PUSH_R0_T1->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, PUSH_R0->transicoes, PUSH_R0_T1->token, strlen(PUSH_R0_T1->token), PUSH_R0_T1);

    

    Estado *PUSH_R1 = (Estado*)smart_malloc(sizeof(Estado));
    PUSH_R1->transicoes = NULL;
    PUSH_R1->chamadas = NULL;
    PUSH_R1->estado = 1;
    HASH_ADD_INT(PUSH_R->estadosTransicoes, estado, PUSH_R1);

    
    
    TransicaoChamada *PUSH_R1_C1 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    PUSH_R1_C1->token = "STACK_IDENTIFIER";
    PUSH_R1_C1->submaquina = "STACK_IDENTIFIER";
    PUSH_R1_C1->estadoResultado = 2;
    HASH_ADD_KEYPTR(hh, PUSH_R1->chamadas, PUSH_R1_C1->token, strlen(PUSH_R1_C1->token), PUSH_R1_C1);


    Estado *PUSH_R2 = (Estado*)smart_malloc(sizeof(Estado));
    PUSH_R2->transicoes = NULL;
    PUSH_R2->chamadas = NULL;
    PUSH_R2->estado = 2;
    HASH_ADD_INT(PUSH_R->estadosTransicoes, estado, PUSH_R2);

    
    
    TransicaoChamada *PUSH_R2_C1 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    PUSH_R2_C1->token = "+";
    PUSH_R2_C1->submaquina = "OPERATIONS";
    PUSH_R2_C1->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, PUSH_R2->chamadas, PUSH_R2_C1->token, strlen(PUSH_R2_C1->token), PUSH_R2_C1);

    TransicaoChamada *PUSH_R2_C2 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    PUSH_R2_C2->token = "?";
    PUSH_R2_C2->submaquina = "OPERATIONS";
    PUSH_R2_C2->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, PUSH_R2->chamadas, PUSH_R2_C2->token, strlen(PUSH_R2_C2->token), PUSH_R2_C2);

    TransicaoChamada *PUSH_R2_C3 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    PUSH_R2_C3->token = ">";
    PUSH_R2_C3->submaquina = "OPERATIONS";
    PUSH_R2_C3->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, PUSH_R2->chamadas, PUSH_R2_C3->token, strlen(PUSH_R2_C3->token), PUSH_R2_C3);

    TransicaoChamada *PUSH_R2_C4 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    PUSH_R2_C4->token = "-";
    PUSH_R2_C4->submaquina = "OPERATIONS";
    PUSH_R2_C4->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, PUSH_R2->chamadas, PUSH_R2_C4->token, strlen(PUSH_R2_C4->token), PUSH_R2_C4);

    TransicaoChamada *PUSH_R2_C5 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    PUSH_R2_C5->token = "<";
    PUSH_R2_C5->submaquina = "OPERATIONS";
    PUSH_R2_C5->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, PUSH_R2->chamadas, PUSH_R2_C5->token, strlen(PUSH_R2_C5->token), PUSH_R2_C5);



    HASH_ADD_KEYPTR(hh, ape->automatos, PUSH_R->title, strlen(PUSH_R->title), PUSH_R);


    return ape;
}

