
#include "ape.h"
#include "../main.h"
#include "../lib/utarray.h"
#include "../lib/uthash.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

/******************************/
/*          WARNING           */
/* This file is autogenerated */
/*                            */
/******************************/

void Automato_copy(void *_dst, const void *_src) {
  Automato *dst = (Automato*)_dst, *src = (Automato*)_src;
  dst->title = src->title;
  dst->estado = src->estado;

  dst->estadosTransicoes = src->estadosTransicoes;
  dst->estadosFinais = src->estadosFinais;
}

UT_icd Automato_icd = {sizeof(Automato), NULL, Automato_copy, NULL};

APE *create_ape() {
    int push_tmp;

    /* Initialize APE */
    APE * ape = (APE*)smart_malloc(sizeof(APE));
    ape->automatos = NULL;
    utarray_new(ape->pilha, &Automato_icd);

    
    
    /* KIPPLE */
    
    Automato *KIPPLE = (Automato*)smart_malloc(sizeof(Automato));
    KIPPLE->estadosTransicoes = NULL;
    KIPPLE->title = "KIPPLE";
    KIPPLE->estado = 0;
    utarray_new(KIPPLE->estadosFinais, &ut_int_icd);


    
    push_tmp = 1; utarray_push_back(KIPPLE->estadosFinais, &push_tmp);


    
    Estado *KIPPLE1 = (Estado*)smart_malloc(sizeof(Estado));
    KIPPLE1->transicoes = NULL;
    KIPPLE1->chamadas = NULL;
    KIPPLE1->estado = 1;
    HASH_ADD_INT(KIPPLE->estadosTransicoes, estado, KIPPLE1);

    
    
    TransicaoChamada *KIPPLE1_C1 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    KIPPLE1_C1->token = "(";
    KIPPLE1_C1->submaquina = "COMANDO";
    KIPPLE1_C1->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, KIPPLE1->chamadas, KIPPLE1_C1->token, strlen(KIPPLE1_C1->token), KIPPLE1_C1);

    TransicaoChamada *KIPPLE1_C2 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    KIPPLE1_C2->token = "NUMBER";
    KIPPLE1_C2->submaquina = "COMANDO";
    KIPPLE1_C2->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, KIPPLE1->chamadas, KIPPLE1_C2->token, strlen(KIPPLE1_C2->token), KIPPLE1_C2);

    TransicaoChamada *KIPPLE1_C3 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    KIPPLE1_C3->token = "STACK_IDENTIFIER";
    KIPPLE1_C3->submaquina = "COMANDO";
    KIPPLE1_C3->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, KIPPLE1->chamadas, KIPPLE1_C3->token, strlen(KIPPLE1_C3->token), KIPPLE1_C3);


    Estado *KIPPLE0 = (Estado*)smart_malloc(sizeof(Estado));
    KIPPLE0->transicoes = NULL;
    KIPPLE0->chamadas = NULL;
    KIPPLE0->estado = 0;
    HASH_ADD_INT(KIPPLE->estadosTransicoes, estado, KIPPLE0);

    
    
    TransicaoChamada *KIPPLE0_C1 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    KIPPLE0_C1->token = "(";
    KIPPLE0_C1->submaquina = "COMANDO";
    KIPPLE0_C1->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, KIPPLE0->chamadas, KIPPLE0_C1->token, strlen(KIPPLE0_C1->token), KIPPLE0_C1);

    TransicaoChamada *KIPPLE0_C2 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    KIPPLE0_C2->token = "NUMBER";
    KIPPLE0_C2->submaquina = "COMANDO";
    KIPPLE0_C2->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, KIPPLE0->chamadas, KIPPLE0_C2->token, strlen(KIPPLE0_C2->token), KIPPLE0_C2);

    TransicaoChamada *KIPPLE0_C3 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    KIPPLE0_C3->token = "STACK_IDENTIFIER";
    KIPPLE0_C3->submaquina = "COMANDO";
    KIPPLE0_C3->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, KIPPLE0->chamadas, KIPPLE0_C3->token, strlen(KIPPLE0_C3->token), KIPPLE0_C3);



    HASH_ADD_KEYPTR(hh, ape->automatos, KIPPLE->title, strlen(KIPPLE->title), KIPPLE);


    ape->automatoAtual = KIPPLE;


    
    /* OPERACAO_PILHA */
    
    Automato *OPERACAO_PILHA = (Automato*)smart_malloc(sizeof(Automato));
    OPERACAO_PILHA->estadosTransicoes = NULL;
    OPERACAO_PILHA->title = "OPERACAO_PILHA";
    OPERACAO_PILHA->estado = 0;
    utarray_new(OPERACAO_PILHA->estadosFinais, &ut_int_icd);


    
    push_tmp = 3; utarray_push_back(OPERACAO_PILHA->estadosFinais, &push_tmp);

    push_tmp = 4; utarray_push_back(OPERACAO_PILHA->estadosFinais, &push_tmp);

    push_tmp = 5; utarray_push_back(OPERACAO_PILHA->estadosFinais, &push_tmp);


    
    Estado *OPERACAO_PILHA4 = (Estado*)smart_malloc(sizeof(Estado));
    OPERACAO_PILHA4->transicoes = NULL;
    OPERACAO_PILHA4->chamadas = NULL;
    OPERACAO_PILHA4->estado = 4;
    HASH_ADD_INT(OPERACAO_PILHA->estadosTransicoes, estado, OPERACAO_PILHA4);

    
    
    TransicaoChamada *OPERACAO_PILHA4_C1 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    OPERACAO_PILHA4_C1->token = "?";
    OPERACAO_PILHA4_C1->submaquina = "OPERACAO_PILHA";
    OPERACAO_PILHA4_C1->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, OPERACAO_PILHA4->chamadas, OPERACAO_PILHA4_C1->token, strlen(OPERACAO_PILHA4_C1->token), OPERACAO_PILHA4_C1);

    TransicaoChamada *OPERACAO_PILHA4_C2 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    OPERACAO_PILHA4_C2->token = "-";
    OPERACAO_PILHA4_C2->submaquina = "OPERACAO_PILHA";
    OPERACAO_PILHA4_C2->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, OPERACAO_PILHA4->chamadas, OPERACAO_PILHA4_C2->token, strlen(OPERACAO_PILHA4_C2->token), OPERACAO_PILHA4_C2);

    TransicaoChamada *OPERACAO_PILHA4_C3 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    OPERACAO_PILHA4_C3->token = "<";
    OPERACAO_PILHA4_C3->submaquina = "OPERACAO_PILHA";
    OPERACAO_PILHA4_C3->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, OPERACAO_PILHA4->chamadas, OPERACAO_PILHA4_C3->token, strlen(OPERACAO_PILHA4_C3->token), OPERACAO_PILHA4_C3);

    TransicaoChamada *OPERACAO_PILHA4_C4 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    OPERACAO_PILHA4_C4->token = "+";
    OPERACAO_PILHA4_C4->submaquina = "OPERACAO_PILHA";
    OPERACAO_PILHA4_C4->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, OPERACAO_PILHA4->chamadas, OPERACAO_PILHA4_C4->token, strlen(OPERACAO_PILHA4_C4->token), OPERACAO_PILHA4_C4);

    TransicaoChamada *OPERACAO_PILHA4_C5 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    OPERACAO_PILHA4_C5->token = ">";
    OPERACAO_PILHA4_C5->submaquina = "OPERACAO_PILHA";
    OPERACAO_PILHA4_C5->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, OPERACAO_PILHA4->chamadas, OPERACAO_PILHA4_C5->token, strlen(OPERACAO_PILHA4_C5->token), OPERACAO_PILHA4_C5);


    Estado *OPERACAO_PILHA1 = (Estado*)smart_malloc(sizeof(Estado));
    OPERACAO_PILHA1->transicoes = NULL;
    OPERACAO_PILHA1->chamadas = NULL;
    OPERACAO_PILHA1->estado = 1;
    HASH_ADD_INT(OPERACAO_PILHA->estadosTransicoes, estado, OPERACAO_PILHA1);

    
    
    TransicaoChamada *OPERACAO_PILHA1_C1 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    OPERACAO_PILHA1_C1->token = "NUMBER";
    OPERACAO_PILHA1_C1->submaquina = "NUMBER";
    OPERACAO_PILHA1_C1->estadoResultado = 5;
    HASH_ADD_KEYPTR(hh, OPERACAO_PILHA1->chamadas, OPERACAO_PILHA1_C1->token, strlen(OPERACAO_PILHA1_C1->token), OPERACAO_PILHA1_C1);

    TransicaoChamada *OPERACAO_PILHA1_C2 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    OPERACAO_PILHA1_C2->token = "STACK_IDENTIFIER";
    OPERACAO_PILHA1_C2->submaquina = "STACK_IDENTIFIER";
    OPERACAO_PILHA1_C2->estadoResultado = 4;
    HASH_ADD_KEYPTR(hh, OPERACAO_PILHA1->chamadas, OPERACAO_PILHA1_C2->token, strlen(OPERACAO_PILHA1_C2->token), OPERACAO_PILHA1_C2);


    Estado *OPERACAO_PILHA5 = (Estado*)smart_malloc(sizeof(Estado));
    OPERACAO_PILHA5->transicoes = NULL;
    OPERACAO_PILHA5->chamadas = NULL;
    OPERACAO_PILHA5->estado = 5;
    HASH_ADD_INT(OPERACAO_PILHA->estadosTransicoes, estado, OPERACAO_PILHA5);

    
    
    TransicaoChamada *OPERACAO_PILHA5_C1 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    OPERACAO_PILHA5_C1->token = ">";
    OPERACAO_PILHA5_C1->submaquina = "OPERACAO_NUMERO";
    OPERACAO_PILHA5_C1->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, OPERACAO_PILHA5->chamadas, OPERACAO_PILHA5_C1->token, strlen(OPERACAO_PILHA5_C1->token), OPERACAO_PILHA5_C1);


    Estado *OPERACAO_PILHA0 = (Estado*)smart_malloc(sizeof(Estado));
    OPERACAO_PILHA0->transicoes = NULL;
    OPERACAO_PILHA0->chamadas = NULL;
    OPERACAO_PILHA0->estado = 0;
    HASH_ADD_INT(OPERACAO_PILHA->estadosTransicoes, estado, OPERACAO_PILHA0);

    
    Transicao *OPERACAO_PILHA0_T1 = (Transicao*)smart_malloc(sizeof(Transicao));
    OPERACAO_PILHA0_T1->token = "?";
    OPERACAO_PILHA0_T1->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, OPERACAO_PILHA0->transicoes, OPERACAO_PILHA0_T1->token, strlen(OPERACAO_PILHA0_T1->token), OPERACAO_PILHA0_T1);

    Transicao *OPERACAO_PILHA0_T2 = (Transicao*)smart_malloc(sizeof(Transicao));
    OPERACAO_PILHA0_T2->token = "-";
    OPERACAO_PILHA0_T2->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, OPERACAO_PILHA0->transicoes, OPERACAO_PILHA0_T2->token, strlen(OPERACAO_PILHA0_T2->token), OPERACAO_PILHA0_T2);

    Transicao *OPERACAO_PILHA0_T3 = (Transicao*)smart_malloc(sizeof(Transicao));
    OPERACAO_PILHA0_T3->token = "<";
    OPERACAO_PILHA0_T3->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, OPERACAO_PILHA0->transicoes, OPERACAO_PILHA0_T3->token, strlen(OPERACAO_PILHA0_T3->token), OPERACAO_PILHA0_T3);

    Transicao *OPERACAO_PILHA0_T4 = (Transicao*)smart_malloc(sizeof(Transicao));
    OPERACAO_PILHA0_T4->token = "+";
    OPERACAO_PILHA0_T4->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, OPERACAO_PILHA0->transicoes, OPERACAO_PILHA0_T4->token, strlen(OPERACAO_PILHA0_T4->token), OPERACAO_PILHA0_T4);

    Transicao *OPERACAO_PILHA0_T5 = (Transicao*)smart_malloc(sizeof(Transicao));
    OPERACAO_PILHA0_T5->token = ">";
    OPERACAO_PILHA0_T5->estadoResultado = 2;
    HASH_ADD_KEYPTR(hh, OPERACAO_PILHA0->transicoes, OPERACAO_PILHA0_T5->token, strlen(OPERACAO_PILHA0_T5->token), OPERACAO_PILHA0_T5);

    

    Estado *OPERACAO_PILHA2 = (Estado*)smart_malloc(sizeof(Estado));
    OPERACAO_PILHA2->transicoes = NULL;
    OPERACAO_PILHA2->chamadas = NULL;
    OPERACAO_PILHA2->estado = 2;
    HASH_ADD_INT(OPERACAO_PILHA->estadosTransicoes, estado, OPERACAO_PILHA2);

    
    
    TransicaoChamada *OPERACAO_PILHA2_C1 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    OPERACAO_PILHA2_C1->token = "STACK_IDENTIFIER";
    OPERACAO_PILHA2_C1->submaquina = "STACK_IDENTIFIER";
    OPERACAO_PILHA2_C1->estadoResultado = 4;
    HASH_ADD_KEYPTR(hh, OPERACAO_PILHA2->chamadas, OPERACAO_PILHA2_C1->token, strlen(OPERACAO_PILHA2_C1->token), OPERACAO_PILHA2_C1);



    HASH_ADD_KEYPTR(hh, ape->automatos, OPERACAO_PILHA->title, strlen(OPERACAO_PILHA->title), OPERACAO_PILHA);

    /* OPERACAO_NUMERO */
    
    Automato *OPERACAO_NUMERO = (Automato*)smart_malloc(sizeof(Automato));
    OPERACAO_NUMERO->estadosTransicoes = NULL;
    OPERACAO_NUMERO->title = "OPERACAO_NUMERO";
    OPERACAO_NUMERO->estado = 0;
    utarray_new(OPERACAO_NUMERO->estadosFinais, &ut_int_icd);


    
    push_tmp = 2; utarray_push_back(OPERACAO_NUMERO->estadosFinais, &push_tmp);

    push_tmp = 3; utarray_push_back(OPERACAO_NUMERO->estadosFinais, &push_tmp);


    
    Estado *OPERACAO_NUMERO1 = (Estado*)smart_malloc(sizeof(Estado));
    OPERACAO_NUMERO1->transicoes = NULL;
    OPERACAO_NUMERO1->chamadas = NULL;
    OPERACAO_NUMERO1->estado = 1;
    HASH_ADD_INT(OPERACAO_NUMERO->estadosTransicoes, estado, OPERACAO_NUMERO1);

    
    
    TransicaoChamada *OPERACAO_NUMERO1_C1 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    OPERACAO_NUMERO1_C1->token = "STACK_IDENTIFIER";
    OPERACAO_NUMERO1_C1->submaquina = "STACK_IDENTIFIER";
    OPERACAO_NUMERO1_C1->estadoResultado = 2;
    HASH_ADD_KEYPTR(hh, OPERACAO_NUMERO1->chamadas, OPERACAO_NUMERO1_C1->token, strlen(OPERACAO_NUMERO1_C1->token), OPERACAO_NUMERO1_C1);


    Estado *OPERACAO_NUMERO0 = (Estado*)smart_malloc(sizeof(Estado));
    OPERACAO_NUMERO0->transicoes = NULL;
    OPERACAO_NUMERO0->chamadas = NULL;
    OPERACAO_NUMERO0->estado = 0;
    HASH_ADD_INT(OPERACAO_NUMERO->estadosTransicoes, estado, OPERACAO_NUMERO0);

    
    Transicao *OPERACAO_NUMERO0_T1 = (Transicao*)smart_malloc(sizeof(Transicao));
    OPERACAO_NUMERO0_T1->token = ">";
    OPERACAO_NUMERO0_T1->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, OPERACAO_NUMERO0->transicoes, OPERACAO_NUMERO0_T1->token, strlen(OPERACAO_NUMERO0_T1->token), OPERACAO_NUMERO0_T1);

    

    Estado *OPERACAO_NUMERO2 = (Estado*)smart_malloc(sizeof(Estado));
    OPERACAO_NUMERO2->transicoes = NULL;
    OPERACAO_NUMERO2->chamadas = NULL;
    OPERACAO_NUMERO2->estado = 2;
    HASH_ADD_INT(OPERACAO_NUMERO->estadosTransicoes, estado, OPERACAO_NUMERO2);

    
    
    TransicaoChamada *OPERACAO_NUMERO2_C1 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    OPERACAO_NUMERO2_C1->token = "?";
    OPERACAO_NUMERO2_C1->submaquina = "OPERACAO_PILHA";
    OPERACAO_NUMERO2_C1->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, OPERACAO_NUMERO2->chamadas, OPERACAO_NUMERO2_C1->token, strlen(OPERACAO_NUMERO2_C1->token), OPERACAO_NUMERO2_C1);

    TransicaoChamada *OPERACAO_NUMERO2_C2 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    OPERACAO_NUMERO2_C2->token = "-";
    OPERACAO_NUMERO2_C2->submaquina = "OPERACAO_PILHA";
    OPERACAO_NUMERO2_C2->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, OPERACAO_NUMERO2->chamadas, OPERACAO_NUMERO2_C2->token, strlen(OPERACAO_NUMERO2_C2->token), OPERACAO_NUMERO2_C2);

    TransicaoChamada *OPERACAO_NUMERO2_C3 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    OPERACAO_NUMERO2_C3->token = "<";
    OPERACAO_NUMERO2_C3->submaquina = "OPERACAO_PILHA";
    OPERACAO_NUMERO2_C3->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, OPERACAO_NUMERO2->chamadas, OPERACAO_NUMERO2_C3->token, strlen(OPERACAO_NUMERO2_C3->token), OPERACAO_NUMERO2_C3);

    TransicaoChamada *OPERACAO_NUMERO2_C4 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    OPERACAO_NUMERO2_C4->token = "+";
    OPERACAO_NUMERO2_C4->submaquina = "OPERACAO_PILHA";
    OPERACAO_NUMERO2_C4->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, OPERACAO_NUMERO2->chamadas, OPERACAO_NUMERO2_C4->token, strlen(OPERACAO_NUMERO2_C4->token), OPERACAO_NUMERO2_C4);

    TransicaoChamada *OPERACAO_NUMERO2_C5 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    OPERACAO_NUMERO2_C5->token = ">";
    OPERACAO_NUMERO2_C5->submaquina = "OPERACAO_PILHA";
    OPERACAO_NUMERO2_C5->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, OPERACAO_NUMERO2->chamadas, OPERACAO_NUMERO2_C5->token, strlen(OPERACAO_NUMERO2_C5->token), OPERACAO_NUMERO2_C5);



    HASH_ADD_KEYPTR(hh, ape->automatos, OPERACAO_NUMERO->title, strlen(OPERACAO_NUMERO->title), OPERACAO_NUMERO);

    /* EXPRESSAO */
    
    Automato *EXPRESSAO = (Automato*)smart_malloc(sizeof(Automato));
    EXPRESSAO->estadosTransicoes = NULL;
    EXPRESSAO->title = "EXPRESSAO";
    EXPRESSAO->estado = 0;
    utarray_new(EXPRESSAO->estadosFinais, &ut_int_icd);


    
    push_tmp = 1; utarray_push_back(EXPRESSAO->estadosFinais, &push_tmp);


    
    Estado *EXPRESSAO0 = (Estado*)smart_malloc(sizeof(Estado));
    EXPRESSAO0->transicoes = NULL;
    EXPRESSAO0->chamadas = NULL;
    EXPRESSAO0->estado = 0;
    HASH_ADD_INT(EXPRESSAO->estadosTransicoes, estado, EXPRESSAO0);

    
    
    TransicaoChamada *EXPRESSAO0_C1 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    EXPRESSAO0_C1->token = "NUMBER";
    EXPRESSAO0_C1->submaquina = "EXP_NUMERO";
    EXPRESSAO0_C1->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, EXPRESSAO0->chamadas, EXPRESSAO0_C1->token, strlen(EXPRESSAO0_C1->token), EXPRESSAO0_C1);

    TransicaoChamada *EXPRESSAO0_C2 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    EXPRESSAO0_C2->token = "STACK_IDENTIFIER";
    EXPRESSAO0_C2->submaquina = "EXP_PILHA";
    EXPRESSAO0_C2->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, EXPRESSAO0->chamadas, EXPRESSAO0_C2->token, strlen(EXPRESSAO0_C2->token), EXPRESSAO0_C2);



    HASH_ADD_KEYPTR(hh, ape->automatos, EXPRESSAO->title, strlen(EXPRESSAO->title), EXPRESSAO);

    /* DIGITO */
    
    Automato *DIGITO = (Automato*)smart_malloc(sizeof(Automato));
    DIGITO->estadosTransicoes = NULL;
    DIGITO->title = "DIGITO";
    DIGITO->estado = 0;
    utarray_new(DIGITO->estadosFinais, &ut_int_icd);


    
    push_tmp = 1; utarray_push_back(DIGITO->estadosFinais, &push_tmp);


    
    Estado *DIGITO0 = (Estado*)smart_malloc(sizeof(Estado));
    DIGITO0->transicoes = NULL;
    DIGITO0->chamadas = NULL;
    DIGITO0->estado = 0;
    HASH_ADD_INT(DIGITO->estadosTransicoes, estado, DIGITO0);

    
    Transicao *DIGITO0_T1 = (Transicao*)smart_malloc(sizeof(Transicao));
    DIGITO0_T1->token = "9";
    DIGITO0_T1->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, DIGITO0->transicoes, DIGITO0_T1->token, strlen(DIGITO0_T1->token), DIGITO0_T1);

    Transicao *DIGITO0_T2 = (Transicao*)smart_malloc(sizeof(Transicao));
    DIGITO0_T2->token = "1";
    DIGITO0_T2->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, DIGITO0->transicoes, DIGITO0_T2->token, strlen(DIGITO0_T2->token), DIGITO0_T2);

    Transicao *DIGITO0_T3 = (Transicao*)smart_malloc(sizeof(Transicao));
    DIGITO0_T3->token = "5";
    DIGITO0_T3->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, DIGITO0->transicoes, DIGITO0_T3->token, strlen(DIGITO0_T3->token), DIGITO0_T3);

    Transicao *DIGITO0_T4 = (Transicao*)smart_malloc(sizeof(Transicao));
    DIGITO0_T4->token = "0";
    DIGITO0_T4->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, DIGITO0->transicoes, DIGITO0_T4->token, strlen(DIGITO0_T4->token), DIGITO0_T4);

    Transicao *DIGITO0_T5 = (Transicao*)smart_malloc(sizeof(Transicao));
    DIGITO0_T5->token = "2";
    DIGITO0_T5->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, DIGITO0->transicoes, DIGITO0_T5->token, strlen(DIGITO0_T5->token), DIGITO0_T5);

    Transicao *DIGITO0_T6 = (Transicao*)smart_malloc(sizeof(Transicao));
    DIGITO0_T6->token = "3";
    DIGITO0_T6->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, DIGITO0->transicoes, DIGITO0_T6->token, strlen(DIGITO0_T6->token), DIGITO0_T6);

    Transicao *DIGITO0_T7 = (Transicao*)smart_malloc(sizeof(Transicao));
    DIGITO0_T7->token = "4";
    DIGITO0_T7->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, DIGITO0->transicoes, DIGITO0_T7->token, strlen(DIGITO0_T7->token), DIGITO0_T7);

    Transicao *DIGITO0_T8 = (Transicao*)smart_malloc(sizeof(Transicao));
    DIGITO0_T8->token = "8";
    DIGITO0_T8->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, DIGITO0->transicoes, DIGITO0_T8->token, strlen(DIGITO0_T8->token), DIGITO0_T8);

    Transicao *DIGITO0_T9 = (Transicao*)smart_malloc(sizeof(Transicao));
    DIGITO0_T9->token = "6";
    DIGITO0_T9->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, DIGITO0->transicoes, DIGITO0_T9->token, strlen(DIGITO0_T9->token), DIGITO0_T9);

    Transicao *DIGITO0_T10 = (Transicao*)smart_malloc(sizeof(Transicao));
    DIGITO0_T10->token = "7";
    DIGITO0_T10->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, DIGITO0->transicoes, DIGITO0_T10->token, strlen(DIGITO0_T10->token), DIGITO0_T10);

    


    HASH_ADD_KEYPTR(hh, ape->automatos, DIGITO->title, strlen(DIGITO->title), DIGITO);

    /* EXP_NUMERO */
    
    Automato *EXP_NUMERO = (Automato*)smart_malloc(sizeof(Automato));
    EXP_NUMERO->estadosTransicoes = NULL;
    EXP_NUMERO->title = "EXP_NUMERO";
    EXP_NUMERO->estado = 0;
    utarray_new(EXP_NUMERO->estadosFinais, &ut_int_icd);


    
    push_tmp = 2; utarray_push_back(EXP_NUMERO->estadosFinais, &push_tmp);


    
    Estado *EXP_NUMERO1 = (Estado*)smart_malloc(sizeof(Estado));
    EXP_NUMERO1->transicoes = NULL;
    EXP_NUMERO1->chamadas = NULL;
    EXP_NUMERO1->estado = 1;
    HASH_ADD_INT(EXP_NUMERO->estadosTransicoes, estado, EXP_NUMERO1);

    
    
    TransicaoChamada *EXP_NUMERO1_C1 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    EXP_NUMERO1_C1->token = ">";
    EXP_NUMERO1_C1->submaquina = "OPERACAO_NUMERO";
    EXP_NUMERO1_C1->estadoResultado = 2;
    HASH_ADD_KEYPTR(hh, EXP_NUMERO1->chamadas, EXP_NUMERO1_C1->token, strlen(EXP_NUMERO1_C1->token), EXP_NUMERO1_C1);


    Estado *EXP_NUMERO0 = (Estado*)smart_malloc(sizeof(Estado));
    EXP_NUMERO0->transicoes = NULL;
    EXP_NUMERO0->chamadas = NULL;
    EXP_NUMERO0->estado = 0;
    HASH_ADD_INT(EXP_NUMERO->estadosTransicoes, estado, EXP_NUMERO0);

    
    
    TransicaoChamada *EXP_NUMERO0_C1 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    EXP_NUMERO0_C1->token = "NUMBER";
    EXP_NUMERO0_C1->submaquina = "NUMBER";
    EXP_NUMERO0_C1->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, EXP_NUMERO0->chamadas, EXP_NUMERO0_C1->token, strlen(EXP_NUMERO0_C1->token), EXP_NUMERO0_C1);



    HASH_ADD_KEYPTR(hh, ape->automatos, EXP_NUMERO->title, strlen(EXP_NUMERO->title), EXP_NUMERO);

    /* CONTROL_STRUCTURE */
    
    Automato *CONTROL_STRUCTURE = (Automato*)smart_malloc(sizeof(Automato));
    CONTROL_STRUCTURE->estadosTransicoes = NULL;
    CONTROL_STRUCTURE->title = "CONTROL_STRUCTURE";
    CONTROL_STRUCTURE->estado = 0;
    utarray_new(CONTROL_STRUCTURE->estadosFinais, &ut_int_icd);


    
    push_tmp = 4; utarray_push_back(CONTROL_STRUCTURE->estadosFinais, &push_tmp);


    
    Estado *CONTROL_STRUCTURE3 = (Estado*)smart_malloc(sizeof(Estado));
    CONTROL_STRUCTURE3->transicoes = NULL;
    CONTROL_STRUCTURE3->chamadas = NULL;
    CONTROL_STRUCTURE3->estado = 3;
    HASH_ADD_INT(CONTROL_STRUCTURE->estadosTransicoes, estado, CONTROL_STRUCTURE3);

    
    Transicao *CONTROL_STRUCTURE3_T1 = (Transicao*)smart_malloc(sizeof(Transicao));
    CONTROL_STRUCTURE3_T1->token = ")";
    CONTROL_STRUCTURE3_T1->estadoResultado = 4;
    HASH_ADD_KEYPTR(hh, CONTROL_STRUCTURE3->transicoes, CONTROL_STRUCTURE3_T1->token, strlen(CONTROL_STRUCTURE3_T1->token), CONTROL_STRUCTURE3_T1);

    
    TransicaoChamada *CONTROL_STRUCTURE3_C1 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    CONTROL_STRUCTURE3_C1->token = "(";
    CONTROL_STRUCTURE3_C1->submaquina = "COMANDO";
    CONTROL_STRUCTURE3_C1->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, CONTROL_STRUCTURE3->chamadas, CONTROL_STRUCTURE3_C1->token, strlen(CONTROL_STRUCTURE3_C1->token), CONTROL_STRUCTURE3_C1);

    TransicaoChamada *CONTROL_STRUCTURE3_C2 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    CONTROL_STRUCTURE3_C2->token = "NUMBER";
    CONTROL_STRUCTURE3_C2->submaquina = "COMANDO";
    CONTROL_STRUCTURE3_C2->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, CONTROL_STRUCTURE3->chamadas, CONTROL_STRUCTURE3_C2->token, strlen(CONTROL_STRUCTURE3_C2->token), CONTROL_STRUCTURE3_C2);

    TransicaoChamada *CONTROL_STRUCTURE3_C3 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    CONTROL_STRUCTURE3_C3->token = "STACK_IDENTIFIER";
    CONTROL_STRUCTURE3_C3->submaquina = "COMANDO";
    CONTROL_STRUCTURE3_C3->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, CONTROL_STRUCTURE3->chamadas, CONTROL_STRUCTURE3_C3->token, strlen(CONTROL_STRUCTURE3_C3->token), CONTROL_STRUCTURE3_C3);


    Estado *CONTROL_STRUCTURE1 = (Estado*)smart_malloc(sizeof(Estado));
    CONTROL_STRUCTURE1->transicoes = NULL;
    CONTROL_STRUCTURE1->chamadas = NULL;
    CONTROL_STRUCTURE1->estado = 1;
    HASH_ADD_INT(CONTROL_STRUCTURE->estadosTransicoes, estado, CONTROL_STRUCTURE1);

    
    
    TransicaoChamada *CONTROL_STRUCTURE1_C1 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    CONTROL_STRUCTURE1_C1->token = "STACK_IDENTIFIER";
    CONTROL_STRUCTURE1_C1->submaquina = "STACK_IDENTIFIER";
    CONTROL_STRUCTURE1_C1->estadoResultado = 2;
    HASH_ADD_KEYPTR(hh, CONTROL_STRUCTURE1->chamadas, CONTROL_STRUCTURE1_C1->token, strlen(CONTROL_STRUCTURE1_C1->token), CONTROL_STRUCTURE1_C1);


    Estado *CONTROL_STRUCTURE0 = (Estado*)smart_malloc(sizeof(Estado));
    CONTROL_STRUCTURE0->transicoes = NULL;
    CONTROL_STRUCTURE0->chamadas = NULL;
    CONTROL_STRUCTURE0->estado = 0;
    HASH_ADD_INT(CONTROL_STRUCTURE->estadosTransicoes, estado, CONTROL_STRUCTURE0);

    
    Transicao *CONTROL_STRUCTURE0_T1 = (Transicao*)smart_malloc(sizeof(Transicao));
    CONTROL_STRUCTURE0_T1->token = "(";
    CONTROL_STRUCTURE0_T1->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, CONTROL_STRUCTURE0->transicoes, CONTROL_STRUCTURE0_T1->token, strlen(CONTROL_STRUCTURE0_T1->token), CONTROL_STRUCTURE0_T1);

    

    Estado *CONTROL_STRUCTURE2 = (Estado*)smart_malloc(sizeof(Estado));
    CONTROL_STRUCTURE2->transicoes = NULL;
    CONTROL_STRUCTURE2->chamadas = NULL;
    CONTROL_STRUCTURE2->estado = 2;
    HASH_ADD_INT(CONTROL_STRUCTURE->estadosTransicoes, estado, CONTROL_STRUCTURE2);

    
    Transicao *CONTROL_STRUCTURE2_T1 = (Transicao*)smart_malloc(sizeof(Transicao));
    CONTROL_STRUCTURE2_T1->token = ")";
    CONTROL_STRUCTURE2_T1->estadoResultado = 4;
    HASH_ADD_KEYPTR(hh, CONTROL_STRUCTURE2->transicoes, CONTROL_STRUCTURE2_T1->token, strlen(CONTROL_STRUCTURE2_T1->token), CONTROL_STRUCTURE2_T1);

    
    TransicaoChamada *CONTROL_STRUCTURE2_C1 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    CONTROL_STRUCTURE2_C1->token = "?";
    CONTROL_STRUCTURE2_C1->submaquina = "OPERACAO_PILHA";
    CONTROL_STRUCTURE2_C1->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, CONTROL_STRUCTURE2->chamadas, CONTROL_STRUCTURE2_C1->token, strlen(CONTROL_STRUCTURE2_C1->token), CONTROL_STRUCTURE2_C1);

    TransicaoChamada *CONTROL_STRUCTURE2_C2 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    CONTROL_STRUCTURE2_C2->token = "(";
    CONTROL_STRUCTURE2_C2->submaquina = "COMANDO";
    CONTROL_STRUCTURE2_C2->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, CONTROL_STRUCTURE2->chamadas, CONTROL_STRUCTURE2_C2->token, strlen(CONTROL_STRUCTURE2_C2->token), CONTROL_STRUCTURE2_C2);

    TransicaoChamada *CONTROL_STRUCTURE2_C3 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    CONTROL_STRUCTURE2_C3->token = "<";
    CONTROL_STRUCTURE2_C3->submaquina = "OPERACAO_PILHA";
    CONTROL_STRUCTURE2_C3->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, CONTROL_STRUCTURE2->chamadas, CONTROL_STRUCTURE2_C3->token, strlen(CONTROL_STRUCTURE2_C3->token), CONTROL_STRUCTURE2_C3);

    TransicaoChamada *CONTROL_STRUCTURE2_C4 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    CONTROL_STRUCTURE2_C4->token = "STACK_IDENTIFIER";
    CONTROL_STRUCTURE2_C4->submaquina = "COMANDO";
    CONTROL_STRUCTURE2_C4->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, CONTROL_STRUCTURE2->chamadas, CONTROL_STRUCTURE2_C4->token, strlen(CONTROL_STRUCTURE2_C4->token), CONTROL_STRUCTURE2_C4);

    TransicaoChamada *CONTROL_STRUCTURE2_C5 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    CONTROL_STRUCTURE2_C5->token = ">";
    CONTROL_STRUCTURE2_C5->submaquina = "OPERACAO_PILHA";
    CONTROL_STRUCTURE2_C5->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, CONTROL_STRUCTURE2->chamadas, CONTROL_STRUCTURE2_C5->token, strlen(CONTROL_STRUCTURE2_C5->token), CONTROL_STRUCTURE2_C5);

    TransicaoChamada *CONTROL_STRUCTURE2_C6 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    CONTROL_STRUCTURE2_C6->token = "-";
    CONTROL_STRUCTURE2_C6->submaquina = "OPERACAO_PILHA";
    CONTROL_STRUCTURE2_C6->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, CONTROL_STRUCTURE2->chamadas, CONTROL_STRUCTURE2_C6->token, strlen(CONTROL_STRUCTURE2_C6->token), CONTROL_STRUCTURE2_C6);

    TransicaoChamada *CONTROL_STRUCTURE2_C7 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    CONTROL_STRUCTURE2_C7->token = "NUMBER";
    CONTROL_STRUCTURE2_C7->submaquina = "COMANDO";
    CONTROL_STRUCTURE2_C7->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, CONTROL_STRUCTURE2->chamadas, CONTROL_STRUCTURE2_C7->token, strlen(CONTROL_STRUCTURE2_C7->token), CONTROL_STRUCTURE2_C7);

    TransicaoChamada *CONTROL_STRUCTURE2_C8 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    CONTROL_STRUCTURE2_C8->token = "+";
    CONTROL_STRUCTURE2_C8->submaquina = "OPERACAO_PILHA";
    CONTROL_STRUCTURE2_C8->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, CONTROL_STRUCTURE2->chamadas, CONTROL_STRUCTURE2_C8->token, strlen(CONTROL_STRUCTURE2_C8->token), CONTROL_STRUCTURE2_C8);



    HASH_ADD_KEYPTR(hh, ape->automatos, CONTROL_STRUCTURE->title, strlen(CONTROL_STRUCTURE->title), CONTROL_STRUCTURE);

    /* COMANDO */
    
    Automato *COMANDO = (Automato*)smart_malloc(sizeof(Automato));
    COMANDO->estadosTransicoes = NULL;
    COMANDO->title = "COMANDO";
    COMANDO->estado = 0;
    utarray_new(COMANDO->estadosFinais, &ut_int_icd);


    
    push_tmp = 1; utarray_push_back(COMANDO->estadosFinais, &push_tmp);


    
    Estado *COMANDO0 = (Estado*)smart_malloc(sizeof(Estado));
    COMANDO0->transicoes = NULL;
    COMANDO0->chamadas = NULL;
    COMANDO0->estado = 0;
    HASH_ADD_INT(COMANDO->estadosTransicoes, estado, COMANDO0);

    
    
    TransicaoChamada *COMANDO0_C1 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    COMANDO0_C1->token = "(";
    COMANDO0_C1->submaquina = "CONTROL_STRUCTURE";
    COMANDO0_C1->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, COMANDO0->chamadas, COMANDO0_C1->token, strlen(COMANDO0_C1->token), COMANDO0_C1);

    TransicaoChamada *COMANDO0_C2 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    COMANDO0_C2->token = "NUMBER";
    COMANDO0_C2->submaquina = "EXPRESSAO";
    COMANDO0_C2->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, COMANDO0->chamadas, COMANDO0_C2->token, strlen(COMANDO0_C2->token), COMANDO0_C2);

    TransicaoChamada *COMANDO0_C3 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    COMANDO0_C3->token = "STACK_IDENTIFIER";
    COMANDO0_C3->submaquina = "EXPRESSAO";
    COMANDO0_C3->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, COMANDO0->chamadas, COMANDO0_C3->token, strlen(COMANDO0_C3->token), COMANDO0_C3);



    HASH_ADD_KEYPTR(hh, ape->automatos, COMANDO->title, strlen(COMANDO->title), COMANDO);

    /* EXP_PILHA */
    
    Automato *EXP_PILHA = (Automato*)smart_malloc(sizeof(Automato));
    EXP_PILHA->estadosTransicoes = NULL;
    EXP_PILHA->title = "EXP_PILHA";
    EXP_PILHA->estado = 0;
    utarray_new(EXP_PILHA->estadosFinais, &ut_int_icd);


    
    push_tmp = 2; utarray_push_back(EXP_PILHA->estadosFinais, &push_tmp);


    
    Estado *EXP_PILHA1 = (Estado*)smart_malloc(sizeof(Estado));
    EXP_PILHA1->transicoes = NULL;
    EXP_PILHA1->chamadas = NULL;
    EXP_PILHA1->estado = 1;
    HASH_ADD_INT(EXP_PILHA->estadosTransicoes, estado, EXP_PILHA1);

    
    
    TransicaoChamada *EXP_PILHA1_C1 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    EXP_PILHA1_C1->token = "?";
    EXP_PILHA1_C1->submaquina = "OPERACAO_PILHA";
    EXP_PILHA1_C1->estadoResultado = 2;
    HASH_ADD_KEYPTR(hh, EXP_PILHA1->chamadas, EXP_PILHA1_C1->token, strlen(EXP_PILHA1_C1->token), EXP_PILHA1_C1);

    TransicaoChamada *EXP_PILHA1_C2 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    EXP_PILHA1_C2->token = "-";
    EXP_PILHA1_C2->submaquina = "OPERACAO_PILHA";
    EXP_PILHA1_C2->estadoResultado = 2;
    HASH_ADD_KEYPTR(hh, EXP_PILHA1->chamadas, EXP_PILHA1_C2->token, strlen(EXP_PILHA1_C2->token), EXP_PILHA1_C2);

    TransicaoChamada *EXP_PILHA1_C3 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    EXP_PILHA1_C3->token = "<";
    EXP_PILHA1_C3->submaquina = "OPERACAO_PILHA";
    EXP_PILHA1_C3->estadoResultado = 2;
    HASH_ADD_KEYPTR(hh, EXP_PILHA1->chamadas, EXP_PILHA1_C3->token, strlen(EXP_PILHA1_C3->token), EXP_PILHA1_C3);

    TransicaoChamada *EXP_PILHA1_C4 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    EXP_PILHA1_C4->token = "+";
    EXP_PILHA1_C4->submaquina = "OPERACAO_PILHA";
    EXP_PILHA1_C4->estadoResultado = 2;
    HASH_ADD_KEYPTR(hh, EXP_PILHA1->chamadas, EXP_PILHA1_C4->token, strlen(EXP_PILHA1_C4->token), EXP_PILHA1_C4);

    TransicaoChamada *EXP_PILHA1_C5 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    EXP_PILHA1_C5->token = ">";
    EXP_PILHA1_C5->submaquina = "OPERACAO_PILHA";
    EXP_PILHA1_C5->estadoResultado = 2;
    HASH_ADD_KEYPTR(hh, EXP_PILHA1->chamadas, EXP_PILHA1_C5->token, strlen(EXP_PILHA1_C5->token), EXP_PILHA1_C5);


    Estado *EXP_PILHA0 = (Estado*)smart_malloc(sizeof(Estado));
    EXP_PILHA0->transicoes = NULL;
    EXP_PILHA0->chamadas = NULL;
    EXP_PILHA0->estado = 0;
    HASH_ADD_INT(EXP_PILHA->estadosTransicoes, estado, EXP_PILHA0);

    
    
    TransicaoChamada *EXP_PILHA0_C1 = (TransicaoChamada*) smart_malloc(sizeof(TransicaoChamada));
    EXP_PILHA0_C1->token = "STACK_IDENTIFIER";
    EXP_PILHA0_C1->submaquina = "STACK_IDENTIFIER";
    EXP_PILHA0_C1->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, EXP_PILHA0->chamadas, EXP_PILHA0_C1->token, strlen(EXP_PILHA0_C1->token), EXP_PILHA0_C1);



    HASH_ADD_KEYPTR(hh, ape->automatos, EXP_PILHA->title, strlen(EXP_PILHA->title), EXP_PILHA);


    return ape;
}

